<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_sub_Maintenance Biller Price Approval</name>
   <tag></tag>
   <elementGuidId>c5c40baf-27f9-4577-be9e-1bcc3f520c33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='biller']/ul/li[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b9f3401e-a173-4a0f-b9d9-613241ecd10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-item</value>
      <webElementGuid>021d4590-2078-4d0a-b0dd-b2c1f0183f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maintenance Biller Price Approval</value>
      <webElementGuid>a52b34fd-e0fe-41cd-a7d2-4e6b98392630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;biller&quot;)/ul[@class=&quot;nav nav-collapse&quot;]/li[2]/a[1]/span[@class=&quot;sub-item&quot;]</value>
      <webElementGuid>4b1442c3-f7e0-4ca1-a51b-68cf58d7b1c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='biller']/ul/li[2]/a/span</value>
      <webElementGuid>976ec397-fac4-4206-864a-4decd2412534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance Biller Price'])[1]/following::span[1]</value>
      <webElementGuid>eb09474b-e157-4df6-9cd9-e62a3fbc2e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Maintenance Approval'])[1]/following::span[3]</value>
      <webElementGuid>c0f9d24d-6486-4bb4-9701-6ad0545a435b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biller Transaction'])[1]/preceding::span[1]</value>
      <webElementGuid>31a5d5c6-f076-4517-bbce-450ea229408a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aggregator List'])[1]/preceding::span[2]</value>
      <webElementGuid>8fecc6c0-ca63-43b9-98f7-0ff9c9ab53ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Maintenance Biller Price Approval']/parent::*</value>
      <webElementGuid>3871672f-ced5-4eba-a477-aeb35731b2fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/ul/li[2]/a/span</value>
      <webElementGuid>8a5cd537-806e-4dfc-beb4-457202d8eb84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Maintenance Biller Price Approval' or . = 'Maintenance Biller Price Approval')]</value>
      <webElementGuid>1bd4f974-85e2-4c86-8546-84dec13b2c20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
