<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Merchant Name_merchantname</name>
   <tag></tag>
   <elementGuidId>1655d36d-8b9a-4992-9737-f662bc0daf2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='merchantname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#merchantname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11caeb76-41a6-4e58-82fe-a488f2f705fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>702fba4b-8378-4b0d-b36e-6c59505e7869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>57687a88-4f47-4c02-902a-e8cdacb64915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>merchantname</value>
      <webElementGuid>2e70db69-e181-45e3-a27c-799cb663dd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>merchantname</value>
      <webElementGuid>893eaec7-859c-45e4-92d9-c381cab88491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;merchantname&quot;)</value>
      <webElementGuid>3d676039-7bc5-42e0-a095-50b90cb487ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='merchantname']</value>
      <webElementGuid>f484d97e-b1f9-4b89-8ee4-7df9762f90d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='optima-search']/div/div[2]/div/input</value>
      <webElementGuid>35cd5890-af6c-4c11-97f1-25ba58028629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a28c8b5d-42fe-44d3-af0c-df48b9733f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'merchantname' and @name = 'merchantname']</value>
      <webElementGuid>f9bbc269-01e1-4540-b7c8-39d8f2b76b81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
