<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_file_doc</name>
   <tag></tag>
   <elementGuidId>6acb0c37-e2c8-4b4a-bf96-0cc27e5d4aa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'csvUrl' and @type = 'file']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>csvUrl</value>
      <webElementGuid>858e9ed7-1861-4e38-9888-9928e320c83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>6910dab2-ec0a-4ebb-b604-eb95aad06fc1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
