<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_waktu_jam1</name>
   <tag></tag>
   <elementGuidId>617337e5-1bd2-4edd-a736-cfe132658caf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = '${jam1}' or . = '${jam1}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5bd3069d-11d5-4ab4-9e61-03970d972d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
                              tw-cursor-pointer
                              tw-flex
                              tw-items-center
                              tw-justify-center
                              tw-h-8
                              tw-text-sm
                              tw-text-center
                              tw-px-5
                               tw-bg-secondary-800 tw-text-white tw-font-semibold
                            </value>
      <webElementGuid>6074b010-ce25-4d6b-9532-05f0342af525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>a36a4d89-48fa-4f42-a9bc-6d883a2ee4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[@class=&quot;modal-background&quot;]/div[@class=&quot;modal-container bounceIn tw-rounded&quot;]/div[@class=&quot;tw-w-full
          tw-h-full
          tw-flex
          tw-flex-col
          tw-justify-between
          tw-bg-white
          tw-rounded
          tw-overflow-hidden
          tw-overflow-y-auto
          tw-sm:w-4/6
          lg:tw-w-1/2
          lg:tw-max-w-2xl&quot;]/div[1]/div[@class=&quot;tw-p-4 tw-overflow-y-auto&quot;]/div[@class=&quot;tw-mb-5&quot;]/div[@class=&quot;tw-w-full tw-relative tw-rounded tw-overflow-hidden tw-bg-blue-10 tw-border&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-relative sm:tw-flex-row tw-justify-between tw-border-b&quot;]/div[@class=&quot;tw-w-full sm:tw-w-1/2 tw-p-4 tw-pb-6 sm:tw-pb-8 sm:tw-p-8&quot;]/div[@class=&quot;tw-w-full sm:tw-w-auto tw-flex tw-justify-center&quot;]/div[@class=&quot;tw-select-none tw-shadow-sm tw-w-full sm:tw-w-auto tw-rounded tw-border&quot;]/div[@class=&quot;tw-flex tw-items-center tw-justify-between&quot;]/div[@class=&quot;tw-border-l tw-w-24 tw-self-center tw-relative tw-px-2 tw-py-2 tw-flex tw-items-center tw-justify-center sm:tw-w-20 sm:tw-px-2&quot;]/div[@class=&quot;tw-fixed tw-w-screen tw-h-screen tw-bg-transparent&quot;]/div[@class=&quot;tw-fixed tw-shadow tw-rounded tw-overflow-y-hidden tw-bg-black tw-h-40 tw-z-100 tw-bg-white tw-flex animation-show&quot;]/div[@class=&quot;tw-overflow-y-auto&quot;]/div[@class=&quot;tw-cursor-pointer
                              tw-flex
                              tw-items-center
                              tw-justify-center
                              tw-h-8
                              tw-text-sm
                              tw-text-center
                              tw-px-5
                               tw-bg-secondary-800 tw-text-white tw-font-semibold&quot;]</value>
      <webElementGuid>c2dad90f-51eb-4f67-b50d-012be2b5b412</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div/div[2]/div[5]/div/div/div[3]/div/div/div/div/div[4]/div/div/div[19]</value>
      <webElementGuid>c402e9f6-6d48-4bdc-b123-55fe327b1210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{{.Voucher}}'])[1]/following::div[50]</value>
      <webElementGuid>f0feae59-3cab-44d4-91b7-6d8c9b7f5514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::div[51]</value>
      <webElementGuid>1d2fe69f-e072-4a70-bc86-8c7446858506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun'])[1]/preceding::div[72]</value>
      <webElementGuid>030ccd1c-2f71-4157-8d90-ecdf21f63a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon'])[1]/preceding::div[72]</value>
      <webElementGuid>53a69d58-e653-4069-90cd-4b1da36338f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='18']/parent::*</value>
      <webElementGuid>8ba5bc32-0c4d-4086-a9cd-4a892ae5c675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]</value>
      <webElementGuid>7f993243-0c96-4950-8700-17809225f7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '18' or . = '18')]</value>
      <webElementGuid>c4277768-bef1-49bb-a8d9-19a98926c1dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
