<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_tahun</name>
   <tag></tag>
   <elementGuidId>d7ea2320-fdc0-4e69-9cd9-59c084fa82ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.rdrYearPicker > select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-root']/div/div/div/div/div[2]/div[5]/div/div[2]/div/div/span/span[3]/select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${tahun}' or . = '${tahun}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>909c3a34-fe3f-4e6c-bf44-f26d294dd175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${tahun}</value>
      <webElementGuid>a05f9b52-2f99-4bcd-8db8-88b5b8577cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[@class=&quot;modal-background&quot;]/div[@class=&quot;modal-container bounceIn tw-rounded&quot;]/div[@class=&quot;tw-w-full
          tw-h-full
          tw-flex
          tw-flex-col
          tw-justify-between
          tw-bg-white
          tw-rounded
          tw-overflow-hidden
          tw-overflow-y-auto
          tw-sm:w-4/6
          lg:tw-w-1/2
          lg:tw-max-w-2xl&quot;]/div[1]/div[@class=&quot;tw-p-4 tw-overflow-y-auto&quot;]/div[@class=&quot;tw-mb-5&quot;]/div[@class=&quot;tw-w-full tw-relative tw-rounded tw-overflow-hidden tw-bg-blue-10 tw-border&quot;]/div[@class=&quot;tw-relative tw-w-full&quot;]/div[@class=&quot;rdrCalendarWrapper tw-w-full rdrDateRangeWrapper tw-w-full&quot;]/div[@class=&quot;rdrMonthAndYearWrapper&quot;]/span[@class=&quot;rdrMonthAndYearPickers&quot;]/span[@class=&quot;rdrYearPicker&quot;]/select[1]</value>
      <webElementGuid>b988c1bc-defc-47e4-bfc5-fd6b4d9bbb9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div/div[2]/div[5]/div/div[2]/div/div/span/span[3]/select</value>
      <webElementGuid>8c791418-67c0-453c-890c-c0e0a4399609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{{.Voucher}}'])[1]/following::select[2]</value>
      <webElementGuid>5bac6e7f-1429-4c57-b336-69db8b484147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::select[2]</value>
      <webElementGuid>861cb7b9-6618-4814-a953-8ccee8e3a5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun'])[1]/preceding::select[1]</value>
      <webElementGuid>57d89ed9-4236-431a-9649-c46a6867707c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon'])[1]/preceding::select[1]</value>
      <webElementGuid>5c2b153f-4922-448f-ae5f-4ad28dc0a42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/select</value>
      <webElementGuid>4d88ce30-0356-48b1-a600-1b1f991112ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '204220412040203920382037203620352034203320322031203020292028202720262025202420232022' or . = '204220412040203920382037203620352034203320322031203020292028202720262025202420232022')]</value>
      <webElementGuid>1fba8305-84b7-4d52-a949-2ad769e62374</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
