<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Promo Campaign</name>
   <tag></tag>
   <elementGuidId>7018fabe-dab4-420e-beac-65bf8f2ae119</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div/div/ul/li[4]/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>27737247-4f2f-48f3-8ce9-3adf6a58d16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
                sidebar-text 
                sidebar-child-show
              </value>
      <webElementGuid>de5fe666-d56c-4217-97b2-b0e4fb9c4301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Promo Campaign</value>
      <webElementGuid>9e401b25-3c17-46fc-a34d-28bd67a65555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app&quot;]/div[@class=&quot;custom-container
      full-sidebar&quot;]/div[@class=&quot;sidebar 
        sidebar-full&quot;]/div[@class=&quot;sidebar-content 
          sidebar-content-full&quot;]/div[@class=&quot;wrapper-sidebar&quot;]/ul[@class=&quot;menu-item-container&quot;]/li[@class=&quot;menu-item
        tw-ease-in
        tw-duration-100
        tw-select-none
        false&quot;]/div[@class=&quot;sidebar-link
          tw-z-30
          false&quot;]/div[@class=&quot;tw-w-full
          tw-flex
          tw-items-center
          tw-justify-between
          tw-gap-x-3&quot;]/div[@class=&quot;tw-flex
            tw-items-center
            tw-justify-between
            tw-w-full&quot;]/span[@class=&quot;sidebar-text 
                sidebar-child-show&quot;]</value>
      <webElementGuid>a8020781-7081-48c0-885a-eee69eec091d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div/ul/li[4]/div/div/div/span</value>
      <webElementGuid>e30ef476-8390-4f1a-ba2b-d77669a7214a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denomination'])[1]/following::span[1]</value>
      <webElementGuid>2a931392-27dd-42e4-95ef-846960dfe274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event Tracking'])[1]/following::span[2]</value>
      <webElementGuid>f83d52cd-19fb-4ab9-9b56-1615862a9ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voucher Management'])[1]/preceding::span[1]</value>
      <webElementGuid>98b4fd24-7032-4ec0-91d2-527576537cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Gift'])[1]/preceding::span[2]</value>
      <webElementGuid>c4089474-a3a6-41ae-b7da-75ee21463807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Promo Campaign']/parent::*</value>
      <webElementGuid>9bf6f20e-b802-4876-81b7-561a6f73e4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/div/span</value>
      <webElementGuid>9186f735-1c33-4b70-9a99-7166475b5106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Promo Campaign' or . = 'Promo Campaign')]</value>
      <webElementGuid>ea8aa5e6-0c8e-472d-84c7-106928d234f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
