<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_amount</name>
   <tag></tag>
   <elementGuidId>39e181c2-649b-46df-a8f8-195c51252eb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qf_46a4c942-b0c1-e822-eb42-8dd4ab6d541c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='q-app']/div/div/div/main/div/div/label[2]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c22e2894-d5cd-4a10-9d7f-8d072d7043ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3968033a-9dea-4086-b78c-731da95836bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>fb8236f4-c667-4b59-9c2e-aad6f2e1a308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan jumlah penarikan</value>
      <webElementGuid>ced283e0-49f3-4c92-984b-f7fb86f538fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qf_46a4c942-b0c1-e822-eb42-8dd4ab6d541c</value>
      <webElementGuid>6a9da531-fa6f-44ba-9513-bcd7f28f8974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>66b52b94-2924-4cd9-bc9d-029245664a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>df9b6ddd-2090-4c22-afb6-ff0b548201ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>f96c58e2-928c-4fbd-9c94-e7cbc04ef31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qf_46a4c942-b0c1-e822-eb42-8dd4ab6d541c&quot;)</value>
      <webElementGuid>b362a220-b811-4dd6-b300-2f69c6b72ae1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qf_46a4c942-b0c1-e822-eb42-8dd4ab6d541c']</value>
      <webElementGuid>1e6241e1-2eff-473f-8936-4eb69817ccfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-app']/div/div/div/main/div/div/label[2]/div/div/div/input</value>
      <webElementGuid>2660fc69-a3d7-4be4-83bc-0315d70609b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d292e8bb-3133-43ae-be72-89307823f03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukkan jumlah penarikan' and @id = 'qf_46a4c942-b0c1-e822-eb42-8dd4ab6d541c' and @type = 'text']</value>
      <webElementGuid>a5bffc5e-5e5d-4e55-8421-5f3f512a0101</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
