<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>backpress-pin</name>
   <tag></tag>
   <elementGuidId>5acd8871-4840-4e52-b1b1-fc8c97a7d6ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.container-pincode > div.backpress.displayBlock</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>86ea723e-6b2e-40d0-a31f-2d78af2e95aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>backpress displayBlock</value>
      <webElementGuid>ad3b1df3-5a7f-49cf-a490-0f5174f1a95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;container-app&quot;]/div[@class=&quot;container-pincode&quot;]/div[@class=&quot;backpress displayBlock&quot;]</value>
      <webElementGuid>7374e3fe-87df-4cca-a40d-2d6dbd43880c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[3]/div</value>
      <webElementGuid>725c7345-f6a4-4ea2-b19f-a956b0948f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OTTOCASH'])[1]/following::div[2]</value>
      <webElementGuid>da609f72-a5c7-461a-bed8-ded52071876f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Pembayaran'])[1]/following::div[32]</value>
      <webElementGuid>af47e21a-9d68-4d03-a581-7afcca75a921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OTTOCASH'])[2]/preceding::div[8]</value>
      <webElementGuid>31677e66-f0af-4e13-82a0-fe0d36ffddce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[11]</value>
      <webElementGuid>b0022c13-9b61-46da-8a1d-148efddc9630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>4e20a95c-f818-43be-a440-9e2f5fedbe4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
