<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>backpress-secure page</name>
   <tag></tag>
   <elementGuidId>22655006-606b-4f42-8e43-b78278b92570</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.backpress.displayBlock.zindex-100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d45c9679-267a-4faf-8c28-ef8bd5897c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>backpress displayBlock zindex-100</value>
      <webElementGuid>939087dd-001b-4d4d-ac51-e5d2b4d3387a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;container-app&quot;]/div[@class=&quot;backpress displayBlock zindex-100&quot;]</value>
      <webElementGuid>0b9718d5-35db-4976-927f-e4b47bc38eb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div</value>
      <webElementGuid>14f5ff4a-d592-45bd-b820-63c642f10070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 21,000'])[1]/preceding::div[2]</value>
      <webElementGuid>b1197cbf-e9ce-4781-8944-58b9b37daa75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Pembayaran'])[1]/preceding::div[4]</value>
      <webElementGuid>225bf00f-cceb-468b-ac36-9fd2cd1c9478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>04b338cc-017b-4d52-a252-68398998516b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
