<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LANJUTKAN</name>
   <tag></tag>
   <elementGuidId>07c99e6d-7e9a-47cf-b602-744ff1fadc0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.button.primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[2]/div/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>810d8b77-9a6a-4ed1-8ead-ed4b5000f5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary</value>
      <webElementGuid>d68d58f3-9761-4aec-b339-82367ca76182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LANJUTKAN</value>
      <webElementGuid>f9e05c09-8cdc-4c82-b5e7-b0197b8af038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;container-app&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;footer&quot;]/div[@class=&quot;buttons-wrapper&quot;]/div[@class=&quot;button primary&quot;]</value>
      <webElementGuid>f4bde056-5cd3-4c4c-9f1b-ce84b761f491</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>98c9304e-9a8d-41cd-8298-3f5261e33583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Pembayaran'])[1]/following::div[29]</value>
      <webElementGuid>1e2a8618-edc4-4aa6-ad97-9c9f23683aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 21,000'])[1]/following::div[31]</value>
      <webElementGuid>40feebce-b8ce-4176-b058-f753a3ec6105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OTTOCASH'])[1]/preceding::div[1]</value>
      <webElementGuid>aa3f5773-b6f8-43f2-a2b8-1979f21c3a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OTTOCASH'])[2]/preceding::div[10]</value>
      <webElementGuid>b8869b37-65c5-43a8-85a5-d8c4390a45e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>6be98e97-d43f-4c6d-86d9-e25a059a2f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LANJUTKAN' or . = 'LANJUTKAN')]</value>
      <webElementGuid>46315ef6-bd46-4e48-a8e0-a58076f3b1ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
