<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Epin2</name>
   <tag></tag>
   <elementGuidId>3af40da6-ce27-475f-a606-6b8d1d19b2a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='tel'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5cffd20-be9a-41f7-9e74-3e2300f7b9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>28ead861-fce4-49fb-b8cf-1caa19d7b957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>2b1f40ee-6e39-401b-8dd1-c1219f63fcda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vue-pincode-input</value>
      <webElementGuid>ebeb3e20-d018-4553-9c74-c8d9a379fa32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;container-app&quot;]/div[@class=&quot;container-pincode&quot;]/div[@class=&quot;box-wrapper displayBlock&quot;]/div[@class=&quot;box-content&quot;]/div[@class=&quot;pincode-wrapper&quot;]/div[@class=&quot;pin-wrapper&quot;]/div[@class=&quot;vue-pincode-input-wrapper default&quot;]/input[@class=&quot;vue-pincode-input&quot;]</value>
      <webElementGuid>2d53d8c4-9dc3-4e05-b7c9-a4690a0de506</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='tel'])[2]</value>
      <webElementGuid>6bcc813a-9942-494c-bbcf-35209a0c42ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[3]/div[2]/div/div/div[3]/div/input[2]</value>
      <webElementGuid>65878ce4-ae76-42ad-8a30-2e8da6417c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>5f51f52b-0d4c-4d27-a1a7-5faefba7d5a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = '-']</value>
      <webElementGuid>cbad65a4-ccdd-47c7-b505-217e6d1f6e7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
