<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Epin6</name>
   <tag></tag>
   <elementGuidId>fd856107-0d04-4b1e-a53c-2aea5fca8426</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='tel'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79390a18-de63-4094-b2de-1f3d5d6b1edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>61979099-5041-4697-ba75-b22edb1d7a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>e2c55a05-db88-4411-9fdd-ad44369ad5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vue-pincode-input</value>
      <webElementGuid>382dc261-fc71-4473-83bb-d49d007f2573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;container-app&quot;]/div[@class=&quot;container-pincode&quot;]/div[@class=&quot;box-wrapper displayBlock&quot;]/div[@class=&quot;box-content&quot;]/div[@class=&quot;pincode-wrapper&quot;]/div[@class=&quot;pin-wrapper&quot;]/div[@class=&quot;vue-pincode-input-wrapper default&quot;]/input[@class=&quot;vue-pincode-input&quot;]</value>
      <webElementGuid>c81d406e-15f6-4e30-a43c-35b5ad7ded73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='tel'])[6]</value>
      <webElementGuid>c6760162-91c1-4b57-b894-dee2b44b697e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[3]/div[2]/div/div/div[3]/div/input[6]</value>
      <webElementGuid>31d5b6f8-7107-4d53-a50e-9b0094db1594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>9a96312f-8aba-4ff1-9f5d-9d12bf5ffff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = '-']</value>
      <webElementGuid>28b8534f-eac4-474d-97c3-f5eb68bca5e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
