<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Epin5</name>
   <tag></tag>
   <elementGuidId>3a63c9d8-ee91-4f43-9833-023c42372852</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='tel'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>944a1969-f47c-414a-846f-6d5bd8194e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>c2221e3f-1423-4d94-9ac5-05d2068d0b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>149e2d39-674d-4a7a-94c7-0cc288ae592e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vue-pincode-input</value>
      <webElementGuid>06478198-5bfb-48aa-86a3-90c216649afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;container-app&quot;]/div[@class=&quot;container-pincode&quot;]/div[@class=&quot;box-wrapper displayBlock&quot;]/div[@class=&quot;box-content&quot;]/div[@class=&quot;pincode-wrapper&quot;]/div[@class=&quot;pin-wrapper&quot;]/div[@class=&quot;vue-pincode-input-wrapper default&quot;]/input[@class=&quot;vue-pincode-input&quot;]</value>
      <webElementGuid>aa10b64a-4ad9-424d-994c-e012f1018c79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='tel'])[5]</value>
      <webElementGuid>b4d01255-bb53-47f3-a81c-91088a2a67e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[3]/div[2]/div/div/div[3]/div/input[5]</value>
      <webElementGuid>6916aca3-5c78-4d68-88b6-99014f56da44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>90a8a5a5-904d-4090-a5e6-e821f660981e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = '-']</value>
      <webElementGuid>96f5ae9d-2f54-43f9-a8af-e0f4bf7708ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
