<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Epin3</name>
   <tag></tag>
   <elementGuidId>fc13c532-5e51-4a02-9e52-5cccf5ca3436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='tel'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e98c6352-ae2a-47f3-bfa7-7af046ef365e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>ddad23b5-ae7e-4391-b009-6db7fe8d8ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>3c0ffd26-efec-4bf5-b9e0-9f737e511574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vue-pincode-input</value>
      <webElementGuid>34a4a435-1bf1-4b09-8a20-a91a071f711f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;container-app&quot;]/div[@class=&quot;container-pincode&quot;]/div[@class=&quot;box-wrapper displayBlock&quot;]/div[@class=&quot;box-content&quot;]/div[@class=&quot;pincode-wrapper&quot;]/div[@class=&quot;pin-wrapper&quot;]/div[@class=&quot;vue-pincode-input-wrapper default&quot;]/input[@class=&quot;vue-pincode-input&quot;]</value>
      <webElementGuid>3638d83b-5dfd-4c28-90cf-fc3d92f3fbc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='tel'])[3]</value>
      <webElementGuid>58407d73-3053-4e51-bfce-ecd5b7278e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[3]/div[2]/div/div/div[3]/div/input[3]</value>
      <webElementGuid>898aaf71-5dce-4b18-9593-2254fd28aae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>52faa7af-0d5a-4d36-8307-2d4a8acc9065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = '-']</value>
      <webElementGuid>f7e3c981-a8b6-4ecc-a37c-8dcb39aeed85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
