<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_sub_Active Product List</name>
   <tag></tag>
   <elementGuidId>4d7abcaa-2c8f-40af-83d5-15523e27f47f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='biller']/ul/li[5]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>85a2a1e5-4b0c-4107-9122-c105b4c739c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-item</value>
      <webElementGuid>e0250063-8b63-41e5-b94e-82f4e8893868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active Product List</value>
      <webElementGuid>2ab782d2-1f5f-4c1a-a43d-98c68b6d4eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;biller&quot;)/ul[@class=&quot;nav nav-collapse&quot;]/li[5]/a[1]/span[@class=&quot;sub-item&quot;]</value>
      <webElementGuid>1f437bae-34cb-444b-9359-6baf499f72b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='biller']/ul/li[5]/a/span</value>
      <webElementGuid>b5894c91-4030-467f-aa44-53450bafc78e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aggregator List'])[1]/following::span[1]</value>
      <webElementGuid>343f0907-aa28-4e71-9179-cd776571133d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biller Transaction'])[1]/following::span[2]</value>
      <webElementGuid>bb49f65e-0022-4249-9492-805db69c7353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Discrepancy Biller Price Midnight Check'])[1]/preceding::span[1]</value>
      <webElementGuid>f5c5eaab-400a-404b-b551-5536f94becea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Discrepancy Biller'])[1]/preceding::span[2]</value>
      <webElementGuid>adab9f17-4d89-44ab-a029-2f3932a24e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Active Product List']/parent::*</value>
      <webElementGuid>72b8b4d4-03e5-4544-b833-f7dd9defebcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/ul/li[5]/a/span</value>
      <webElementGuid>cfe13d52-229e-4ca9-9dd6-0f7f1cde8c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Active Product List' or . = 'Active Product List')]</value>
      <webElementGuid>7b115038-faac-43ad-9fff-90a00ff5e0f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
