<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_Biller Management</name>
   <tag></tag>
   <elementGuidId>6400dcef-5de8-419e-85e4-4d16a854ca4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='access-menu']/li[3]/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a67185b5-d840-47e7-93ff-f49793d10f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Biller Management</value>
      <webElementGuid>be6dd160-b5ca-456f-9814-2120f3de397c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;access-menu&quot;)/li[@class=&quot;nav-item&quot;]/a[1]/p[1]</value>
      <webElementGuid>eec253f3-7ec9-4293-a171-eb416e3b5f24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='access-menu']/li[3]/a/p</value>
      <webElementGuid>9dc28963-b58b-431d-85d3-38bcc3b33da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Maintenance Approval'])[1]/following::p[1]</value>
      <webElementGuid>1217e49b-5199-4b64-960a-06405801e556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Maintenance'])[1]/following::p[1]</value>
      <webElementGuid>a1523b30-ba4c-47ac-bada-8decd7107bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance Biller Price'])[1]/preceding::p[1]</value>
      <webElementGuid>fa780178-ce31-4d73-9c09-39d38efb68fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance Biller Price Approval'])[1]/preceding::p[1]</value>
      <webElementGuid>f90a02a5-615b-4971-9041-bdfbe0762cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Biller Management']/parent::*</value>
      <webElementGuid>8adaf9f6-f4d9-4969-8038-178bf72f89bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/p</value>
      <webElementGuid>9c78ec69-39ee-4fd3-8159-84d6afffdb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Biller Management' or . = 'Biller Management')]</value>
      <webElementGuid>f7cc75a3-c7d0-41b9-b104-6492cc925b44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
