<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ref. Number_reffnumber</name>
   <tag></tag>
   <elementGuidId>d15dea38-778e-4f8a-b7d6-e30d6d9dac98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reffnumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reffnumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db822719-5ab0-4814-9bce-717213c132d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6493d59d-9bdb-4c7f-bc6d-718cc8b3a97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2c66d843-1c8f-41e7-9a86-4614c350f0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reffnumber</value>
      <webElementGuid>35e7a5d3-c881-44bb-b955-9c19a59db94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reffnumber</value>
      <webElementGuid>2ae62919-169c-4246-b315-872d634cf931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reffnumber&quot;)</value>
      <webElementGuid>d6de572a-8445-467a-8e6a-8f3f6d5a34df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reffnumber']</value>
      <webElementGuid>7f0008ef-7d4b-4583-8d1e-c5b135a8474c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='optima-search']/div[2]/div[3]/div/input</value>
      <webElementGuid>bfaa465a-4511-4221-89df-1b7e744de473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/input</value>
      <webElementGuid>8b0bb2e1-1c91-4604-8746-1cd158bfe7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'reffnumber' and @name = 'reffnumber']</value>
      <webElementGuid>c26707a5-c387-4c07-bde8-1d56fd787c10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
