<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Periode_perioddate</name>
   <tag></tag>
   <elementGuidId>f5096806-1fea-40e4-9295-54da3679f2e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#perioddate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='perioddate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5bb6f79-13b4-4651-b0d7-a6f67d0d35ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3b867845-a27f-403a-8619-701444c024fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e34a7afc-e674-4973-bdd8-d1e8194c086e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>perioddate</value>
      <webElementGuid>1388b1b9-390f-4b8b-8a00-a56f78c0b1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>perioddate</value>
      <webElementGuid>64520c9e-e381-4b3e-a304-f3e72e9d89a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start date to End date</value>
      <webElementGuid>f2255068-d61c-4976-bf4f-3ad09f8d1d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;perioddate&quot;)</value>
      <webElementGuid>333ac8dd-1371-43f8-a9d1-9a4254493efa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='perioddate']</value>
      <webElementGuid>1ce89cb0-adb0-4284-a9de-f276c474f062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='optima-search']/div[2]/div/div/input</value>
      <webElementGuid>627d5e21-69a4-4885-a983-76811c1b6f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>a1faf9ab-3100-4a89-bf51-33fe5ec3211b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'perioddate' and @name = 'perioddate' and @placeholder = 'Start date to End date']</value>
      <webElementGuid>09347b14-5ffc-474f-9ff2-a1914dc35dbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
