<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Partner Refund ID_partnerrefundid</name>
   <tag></tag>
   <elementGuidId>11d564e8-f534-4266-95e4-65f628e2b3bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#partnerrefundid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='partnerrefundid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed97ef9b-e9de-4852-a62b-146b85f8a3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4978e864-10e1-4790-a505-02d9d0f5077e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c9c1dd27-edbf-4b1f-9f94-9609655c4225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partnerrefundid</value>
      <webElementGuid>1f6656a3-5f26-4d0f-8a2c-481128027522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>partnerrefundid</value>
      <webElementGuid>cbf26a81-5907-4749-b2d3-6d9e24bf53b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partnerrefundid&quot;)</value>
      <webElementGuid>f87c26c9-1239-4d0a-a47f-faca2fb9b1e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='partnerrefundid']</value>
      <webElementGuid>4d4fd84a-eba6-4de9-bccd-492380d292f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='optima-search']/div/div[3]/div/input</value>
      <webElementGuid>a5a2e153-cbe6-482e-bd45-dc974e40ff59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>951041df-d15f-491e-a821-763927a46e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'partnerrefundid' and @name = 'partnerrefundid']</value>
      <webElementGuid>2f245279-de48-47fd-bcd1-634056eb1df1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
